require('config.lualine')
require('config.nvim_tree')
require('config.nvim_compe')
require('config.lspsaga')
require('config.lspkind')
require('config.neorg')
require('config.nvim_comment')
require('config.which-key')
